### ISSUE TITLE
ImportError: No module named 'evolution'

### ISSUE THREAD

**Issue by LiaqatAli007** [subpath/neuro-evolution#1]
Hi,
I just pip installed the neuro-evolution into my environment but it is showing the issue that "No module named evolution".

**Comment by subpath** [comment]
Hi! Thanks for the feedback!
I updated readme, 
please use
`from neuro_evolution import evolution`
 and then 
`search = evolution.NeuroEvolution(generations = 10, population = 10, params=params)`

**Comment by LiaqatAli007** [comment]
Thank you for your feedback. Additionally, is there any procedure for using cross validation (CV) like k-fold?

**Comment by subpath** [comment]
Do you mean am I using k-fold CV inside this package?
No, there is no CV inside.
