### ISSUE TITLE
Requiring data

### ISSUE THREAD

**Issue by adilahrashid** [subpath/neuro-evolution#2]
Hi Alexander,

It would be great if you add your dataset that works well with this code.
Also, may I request the code on how to read the data, split to train and test dataset as well.
The 1st error I got when trying this code was x_train is not defined. 

Keep up the good job!
Thanks!

**Comment by subpath** [comment]
Hi! Sorry for the delay - busy weak. 
I added an example:
https://github.com/subpath/neuro-evolution/blob/master/examples/Example.ipynb

Let me know if you have any questions!

Cheers, 
Alex
